INSERT INTO PUBLIC.ARCIERI(ID, NOME, COGNOME, SESSO) VALUES
  (65, 'Pippo', 'Pippo', 'M'),
  (66, 'Pluto', 'Pluto', 'M'),
  (67, 'Paperino', 'Paperino', 'M'),
  (68, 'Paperina', 'Paperina', 'F');
INSERT INTO PUBLIC.CONFIGURAZIONE(ID,DATA_ANNO_SOCIETARIO) VALUES(1,'1/10');
INSERT INTO PUBLIC.DIVISIONI(ID, DESCRIZIONE, DEFAULT_GROUP, ENABLED) VALUES
  (3, 'Giovanili', 1, 1),
  (4, 'Femminile', 1, 1),
  (5, 'Arco nudo', 1, 1),
  (6, 'Compound', 1, 1),
  (102, 'V.I.', 0, 1),
  (133, 'Maschile', 1, 1),
  (2, 'Master', 0, 1),
  (1, 'Senior', 0, 1);

INSERT INTO PUBLIC.TIPI_GARA (ID,NOME,DESCRIZIONE) VALUES
  (1,'FIOCCHI','Fiocchi'),
  (2,'INDOOR','Indoor'),
  (3,'SCONTRI IND.','Scontri Indoor'),
  (4,'SCONTRI OUT.','Scontri outdoor');
INSERT INTO PUBLIC.USER (ID,USERNAME,PASSWORD,ACTIVE) VALUES (1,'andrea','$2a$10$kcyNi7jCFHeqop.nbMaXCu6hXReykAJzpys6ciYrs4jwSPtqpeYMW',1); --'prova' encoded
INSERT INTO PUBLIC.USER (ID,USERNAME,PASSWORD,ACTIVE) VALUES (2,'view','$2a$10$kcyNi7jCFHeqop.nbMaXCu6hXReykAJzpys6ciYrs4jwSPtqpeYMW',1); --'prova' encoded
INSERT INTO PUBLIC.ROLE (ID,NAME) VALUES (1,'ROLE_ADMIN');
INSERT INTO PUBLIC.ROLE (ID,NAME) VALUES (2,'ROLE_EDIT');
INSERT INTO PUBLIC.ROLE (ID,NAME) VALUES (3,'ROLE_VIEW');
INSERT INTO PUBLIC.USER_ROLES (USER_ID,ROLES_ID) VALUES (1,1);
INSERT INTO PUBLIC.USER_ROLES (USER_ID,ROLES_ID) VALUES (1,2);
INSERT INTO PUBLIC.USER_ROLES (USER_ID,ROLES_ID) VALUES (2,3);

INSERT INTO TEMPLATEGARA VALUES (1,'Punteggio singolo',1);
INSERT INTO TEMPLATEGARA VALUES (2,'Punteggio scontro',3);
INSERT INTO TEMPLATEPUNTEGGIO VALUES (1,'Punteggio',0,1);
INSERT INTO TEMPLATEPUNTEGGIO VALUES (2,'Numero di vittorie',0,2);
INSERT INTO TEMPLATEPUNTEGGIO VALUES (3,'Totale punti impatti',1,2);
INSERT INTO TEMPLATEPUNTEGGIO VALUES (4,'Totale punti scontri',2,2);


